---
title: "一道面试题"
date: 2018-01-10T22:15:22+08:00
draft: false
---

今天在知乎上看到一道JavaScript面试题:

```javascript
var x = 20;
var a = {
  x : 15,
  fn : function(){
    var x = 30;
    return function(){
       return this.x;
     };
   }
};
console.log(a.fn());
console.log((a.fn())());
console.log(a.fn()());
console.log(a.fn()() == (a.fn())());
console.log(a.fn().call(this));
console.log(a.fn().call(a));
```

第一个console.log输出:

```javascript
function (){
    return this.x;
}
```

第二个console.log输出:

```javascript
20
```

根据第一个输出，我们可以把第二个式子改为

```javascript
console.log((function (){
     return this.x;
})());
```

这里的this指向全局对象，立即执行a.fn()返回全局变量x。
第三个console.log输出:

```javascript
20
```

这里和第二输出的式子有些不同，函数式少了一个括号

 

```javascript
console.log(function (){
  return this.x;
}());
```

我们在控制台输入下面的代码:

```javascript
function (){
  return this.x;	
}()； //报错
```

这时控制台会报错，而当我们在函数外面加一个括号时:

```javascript
(function (){
  return this.x;
})()； //输出this.x
```

第一种情况，我们立即执行的是一个匿名函数，而匿名函数属于函数声明(使用function关键字声明一个函数，然后指定一个函数名，类似于function&nbsp;myFn(){….}的形式)，如果我们要在后面加括号立即调用，则这个函数必须是函数表达式(类似于var myFn=function(){…}的形式），所以第二个函数能正常执行。而

```javascript
console.log(function (){
  return this.x;
}());

```

能正常执行，是因为外面套了一个`console.log();`从而使

 

```javascript
function (){
  return this.x;
}()； //报错

```

成为了一个函数表达式，因此不会报错。
第四个输出true，很好理解。
第五个考察call()这个函数，因为this指向的是全局变量，所以call(this)仍然指向全局变量x=20,所以输出20。
第六个输出中的call()函数把this指针指向了a，所以x的值变成了15